language: node_js
node_js:
  - node
before-install:
  - npm install
script:
  - npm run build --prod
  -cd dist

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
